version: '2'

networks:
  webshop-net:
    driver: bridge
    
services:
  basket:
    image: basketimage:latest
    depends_on:
      - "postgres_image"
    build:
      context: ./basket/basket
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=basketdb;username=postgres;password=postgres"
    networks:
      - webshop-net
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "basketdb"
    networks:
      - webshop-net

  marketing:
    build: marketing/.
    networks:
      - webshop-net
    depends_on:
      - "mongodb"
    ports:
      - "3003:3000"
    environment:
      PORT: 3000
      DB_IP: mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - webshop-net
    restart: always

  payment:
    build: orderPayment/.
    container_name: "payment"
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_DB: "iws"
      POSTGRES_USER: "iws"
      POSTGRES_PASS: "iws"
    ports:
      - "3004:8080"
    depends_on:
      - "paymentdb"
    networks:
      - webshop-net

  paymentdb:
    container_name: "payment_db"
    image: postgres:10.11
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "iws"
      POSTGRES_USER: "iws"
      POSTGRES_PASSWORD: "iws"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webshop-net

  productcatalog:
    build: productcatalog/.
    container_name: "productcatalog"
    environment:
      DB_CONNECTION_STRING: "jdbc:mysql://productcatalogdb:3306/catalogdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
    ports:
    - "3006:8080"
    depends_on:
      - "productcatalogdb"
    networks:
      - webshop-net

  productcatalogdb:
    image: mysql:latest
    container_name: "productcatalogdb"
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-pw"
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
      - webshop-net

  api-gateway:
    build: API-Gateway/.
    networks:
      - webshop-net
    ports:
      - "3005:3000"
    environment:
      MARKETING_IP: marketing
      BASKET_IP: basket
      PAYMENT_IP: payment

volumes:
  postgres_data:
  mysql_data: